### PR TITLE
Gui buttons

### PR DESCRIPTION
**Pull request by Spyder-Monkey**
GUI layout

### CODE REVIEW

**Review by astruxie — CHANGES_REQUESTED** [review]
Coding Standards: Good

Comments: View.py could use some comments and spacing. It's got a lot goin on.

Logic: Good

Error Handling: Good

Code Decisions: Good

**Comment by manwellaa** [comment]
Hey guys should we consider making the view a class, information from the view has to be passed to the controller and subsequently the model, if we make it into a class we can simply pass the view to the controller, also the event loop should be in the controller.

**Comment by astruxie** [comment]
> Hey guys should we consider making the view a class, information from the view has to be passed to the controller and subsequently the model, if we make it into a class we can simply pass the view to the controller, also the event loop should be in the controller. 

Ah, yes I agree

**Comment by aaheinba** [comment]
> Hey guys should we consider making the view a class, information from the view has to be passed to the controller and subsequently the model, if we make it into a class we can simply pass the view to the controller, also the event loop should be in the controller.

Yeah I start convert it

**Review by astruxie — APPROVED** [review]
Alright, good now.

**Pull request merged**
