### PR TITLE
Relationship Class created

### PR DESCRIPTION
**Pull request by manwellaa**
Need the class 'class' to be implemented to finish.

### CODE REVIEW

**Comment by Spyder-Monkey** [comment]
Does the listOfRelationships hold every relationship that exists?

**Comment by astruxie** [comment]
> Does the listOfRelationships hold every relationship that exists?

I think it will have to be similar to the classIndex list. A global variable declared outside of the class. This way, we can see all of them at once. 

Also, I *think* this code will allow you to make duplicate relationships if you reverse the source and destination. The order shouldn't matter, right? foo -> bar is the same as bar -> foo?

**Comment by manwellaa** [comment]
the class model should/could hold the list of the relationships, I used the list for myself to visualize the flow. I assume the relationship class will be a subclass of the class class so however you guys decide to store the list of relationships won't matter too much as long as it's a list.

**Comment by Spyder-Monkey** [comment]
Why are you trying to merge into develop if this is not finished?

**Comment by manwellaa** [comment]
The functions are defined so others can use them, also what do you want to add?

**Comment by Spyder-Monkey** [comment]
Looking at your comments, there are a couple places that need to implement some kind of search, there are no comments explaining what the code does, and implementation of the UMLClass class.

**Comment by manwellaa** [comment]
Not sure if you read the code or my past comments, I’m waiting for the class “class” to implement the search.

**Comment by manwellaa** [comment]
I can walk you through the code if needed

**Comment by Spyder-Monkey** [comment]
Not sure if you looked at the develop branch but that class has already been merged. It's called UMLClass

**Comment by manwellaa** [comment]
I saw that but this code was committed and written before that merge, outside of the search do you have any issues?

**Comment by astruxie** [comment]
> 

My UMLClass has a method to find if a class object exists in the classIndex list and return it's index if it does exist, is that the search you mean?

**Comment by manwellaa** [comment]
I’ve got another local branch with your search implemented, other than the search is there anything else you would want to change or include?

**Comment by Spyder-Monkey** [comment]
There are no comments explaining the code. And why would you not push the one with the search implemented? Also, the sprint requirements only have Add and Delete. Where is Edit coming from?

**Comment by manwellaa** [comment]
So you’re saying we don’t need an edit relationship function? This is the best time to make changes

**Comment by Spyder-Monkey** [comment]
Just start by commenting your code

**Comment by manwellaa** [comment]
What is it you’re having trouble understanding in the code?

**Comment by Spyder-Monkey** [comment]
i'm not having trouble. it's just a common decency to comment your code for the future for you and everyone else in the group. i shouldn't have to explain that to someone in a higher level class

**Comment by manwellaa** [comment]
Ok. Will the relationship class be a subclass of the class model?

**Pull request closed without merging**
